name: build-and-test
on:
 workflow_dispatch:
 
jobs:
  setup-secrets:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data/vault/conjurtest/conjurtest/username|USER;data/vault/conjurtest/conjurtest/password|PASS"
    secrets:
      CONJUR_URL: ${{ secrets.CONJUR_URL }}
      CONJUR_ACCOUNT: ${{ secrets.CONJUR_ACCOUNT }}
      CONJUR_HOST_ID: ${{ secrets.CONJUR_HOST_ID }}   # e.g., host/github/myapp-ci
      CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}
#      CONJUR_CERT: ${{ secrets.CONJUR_CERT }}         # optional
 
  use-secret:
    runs-on: ubuntu-latest
    needs: [setup-secrets]
    steps:
     - name: Use masked Wiz secrets
     - run: |
        env:
         USER: ${{ env.USER }}
         PASS: ${{ env.PASS }}
         echo "Secret1 length: $(echo '${USER}' | wc -c)
  
  
  
  
#  test:
#    needs: setup-secrets
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - run: ./run-tests.sh
#        env:
#          USER: ${{ env.USER }}
#          PASS: ${{ env.PASS }}
