name: Platform Source Code
 
permissions:
  id-token: write
  contents: read
 
on:
  workflow_dispatch:
 
jobs:
  workflow-1:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data%2Fvault%2Fconjurtest%2Fconjurtest%2Fusername"
    secrets: inherit
 
  workflow-2:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data%2Fvault%2Fconjurtest%2Fconjurtest%2Fpassword"
    secrets: inherit
 
  workflow-3:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data%2Fvault%2Fconjurtest%2Fconjurtest%2Faddress"
    secrets: inherit
 
  use-wiz_client_secret:
    runs-on: ubuntu-latest
    needs: [workflow-1, workflow-2, workflow-3]
    steps:
      - name: Show masked Wiz secrets
        run: |
          echo "${{ needs.workflow-1.outputs.wiz_client_secret }}"
          echo "::add-mask::${{ needs.workflow-1.outputs.wiz_client_secret }}"
          echo "::add-mask::${{ needs.workflow-2.outputs.wiz_client_secret }}"
          echo "::add-mask::${{ needs.workflow-3.outputs.wiz_client_secret }}"
          echo "Secret1 length: $(echo '${{ needs.workflow-1.outputs.wiz_client_secret }}' | wc -c)"
          echo "Secret2 length: $(echo '${{ needs.workflow-2.outputs.wiz_client_secret }}' | wc -c)"
          echo "Secret3 length: $(echo '${{ needs.workflow-3.outputs.wiz_client_secret }}' | wc -c)"
