name: Platform Source Code
 
permissions:
  id-token: write
  contents: read
 
on:
  workflow_dispatch:
 
jobs:
  workflow-1:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data/vault/conjurtest/conjurtest/username"
    secrets: inherit
 
  workflow-2:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data/vault/conjurtest/conjurtest/password"
    secrets: inherit
 
  workflow-3:
    uses: testid1/ConjurCalling/.github/workflows/ConjurCalling.yaml@main
    with:
      CONJUR_VARIABLE_PATH: "data/vault/conjurtest/conjurtest/address"
    secrets: inherit
 
  use-wiz_client_secret:
    runs-on: ubuntu-latest
    needs: [workflow-1, workflow-2, workflow-3]
    outputs: 
      caller-output1: ${{ jobs.workflow-1.outputs.wiz_client_secret }}
    steps:
      - name: Show masked Wiz secrets
        run: |
           echo "Secret1 length: $(echo '${{ needs.use-wiz_client_secret.outputs.caller-output1 }}' | wc -c)"
#          echo "::add-mask::${{ needs.workflow-1.outputs.wiz_client_secret }}"
#          echo "::add-mask::${{ needs.workflow-2.outputs.wiz_client_secret }}"
#          echo "::add-mask::${{ needs.workflow-3.outputs.wiz_client_secret }}"
#          echo "Secret1 length: $(echo '${{ needs.workflow-1.outputs.wiz_client_secret }}' | wc -c)"
#          echo "Secret2 length: $(echo '${{ needs.workflow-2.outputs.wiz_client_secret }}' | wc -c)"
#          echo "Secret3 length: $(echo '${{ needs.workflow-3.outputs.wiz_client_secret }}' | wc -c)"
